name: video_retrieval_v3_cp2

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # --- Conda packages (pinned) ---
  - python=3.10.19
  - ffmpeg=4.2.2
  - pip=25.3
  - faiss-gpu=1.13.2

  # --- Pip packages (pinned) ---
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121

      - scenedetect[opencv]==0.6.7.1
      - ffmpeg-python==0.2.0
      - numpy==2.2.6
      - pandas==2.3.3
      - transformers==4.57.3
      - easydict==1.13
      - timm==1.0.23
      - loguru==0.7.3
      - gdown==5.2.0

      - git+https://github.com/lyakaap/ISC21-Descriptor-Track-1st@228aad34ac5d5be77bf026dcda0a7b97d74da210
